language: java

before_script:

script:
  - mvn test

deploy:
  provider: gae
  keyfile: GarbageHound-56e7fa2329f9.json
  project: garbagehound-142922

before_install:
  - cd garbagehound
  - openssl aes-256-cbc -K $encrypted_fa1e0588f3f4_key -iv $encrypted_fa1e0588f3f4_iv
    -in GarbageHound-56e7fa2329f9.json.enc -out GarbageHound-56e7fa2329f9.json -d
